name: tagpr
on:
  push:
    branches:
    - "main"
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
    - id: tagpr
      run: |
        make install
        echo '::echo::on'
        tagpr
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
